name: Run Tests

on:
  push:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name:  Checkout do repositório
        uses: actions/checkout@v3

      - name:  Setup do Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'  

      - name:  Cache de dependências (node_modules)
        uses: actions/cache@v3
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name:  Instalar dependências
        run: npm install

      # Passo para verificar a instalação do Jest
      - name:  Verificar instalação do Jest
        run: npx jest --version

      - name:  Executar testes com Jest
        run: npm test
