name: Run Tests

on:
  push:
   
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'

      - name: Instalar dependências
        run: |
          npm ci
          npm install -g jest@latest

      - name: Verificar estrutura de testes
        run: |
          echo "Arquivos de teste encontrados:"
          ls -R tests/
          echo "Versão do Jest: $(jest --version)"

      - name: Executar teste específico
        run: npx jest "tests/JS Completo.test.js" --ci --verbose

      - name: Executar todos os testes (opcional)
        if: always()
        run: npx jest --ci --coverage

      - name: Upload de resultados
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: test-results
          path: |
            coverage/
            jest-stare/